---
version: '3.42.1'

includes:
  common: assets/task/common.yml

vars:
  INSPEC_COMPOSE_SERVICE: chef/inspec:5.22.76
  INSPEC_PROFILES: ['ansible-baseline']
  REPO: https://raw.githubusercontent.com/sommerfeld-io/.github

tasks:

  cleanup:
    desc: 'Cleanup the environment'
    cmds:
      - find . -type f -exec chmod +r {} +

  # ===============================================================================================

  lint:
    desc: 'Run all project linters outside of Dockerfile linters'
    cmds:
      - for: ['yaml', 'workflows', 'filenames', 'folders', 'markdown-links']
        cmd: docker compose up lint-{{ .ITEM }} --exit-code-from lint-{{ .ITEM }}
