---
version: '3.42.1'

includes:
  common: assets/task/common.yml

vars:
  INSPEC_COMPOSE_SERVICE: chef/inspec:5.22.76
  INSPEC_PROFILES: ['ansible-baseline']
  REPO: https://raw.githubusercontent.com/sommerfeld-io/.github

tasks:

  cleanup:
    desc: 'Cleanup the environment'
    cmds:
      - docker compose down --remove-orphans
      - docker container prune -f
      - docker volume prune -f
      - rm -rf .cache
      - sudo rm -rf .ansible
      - sudo rm -rf .devcontainer/ops
      - rm -rf node_modules
      - rm -rf target
      - find . -type f -exec chmod +r {} +
      - find . -type f -exec chmod ugo+r {} +
      - find . -type d -exec chmod 755 {} +
      - find . -name "*.sh" -type f -exec chmod +x {} +

  # ===============================================================================================

  lint:
    desc: 'Run all project linters outside of Dockerfile linters'
    cmds:
      - for: ['yaml', 'workflows', 'filenames', 'folders', 'markdown-links']
        cmd: docker compose up lint-{{ .ITEM }} --exit-code-from lint-{{ .ITEM }}
