---
# @file ci.yml
# @brief Github Actions workflow that handles continuous integration tasks like running linters, building the app and running automated tests.
#
# @description This GitHub Actions workflow is designed for continuous integration and automates
# essential tasks such as code linting, building the application, and running automated tests.
# It ensures code quality, catches errors early, and provides developers with quick feedback on
# their changes. The workflow triggers automatically when new code is pushed to the remote repo
# and automatically each night, making it an integral part of the development process to maintain
# a stable and reliable codebase.
name: CI

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    branches-ignore:
      - dependabot/**
  schedule:
    - cron: '0 3 * * 1' # https://crontab.guru/#0_2_*_*_1

permissions:
  contents: read

jobs:
  module-ci-lint:
    uses: sommerfeld-io/dev-environment-config/.github/workflows/module-ci-lint.yml@main

  on-failure:
    runs-on: ubuntu-latest
    needs: ['module-ci-lint']
    if: failure()
    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
