---
# @file docs-as-code.yml
# @brief Github Actions workflow that generates Asciidoc documentation based on source code from this repo and updates the projects README file.
#
# @description This GitHub Actions workflow serves the purpose of generating Asciidoc documentation
# based on the source code from the repository and updating the project's ``README.adoc`` based on
# contents from the Antora docs. It is designed to automatically trigger whenever new code is pushed
# to the remote repository. Additionally, it is scheduled to run each night to ensure the
# documentation is up-to-date.
#
# By utilizing this workflow, the project ensures that the Asciidoc documentation stays in sync with
# the latest code changes. This leads to improved documentation quality and better project
# understanding.


name: Generate Docs (as Code)

on:
  push:
    # branches: [ "main", "feat/*", "release/*" ]
    branches-ignore:
      - dependabot/**

permissions:
  contents: write
  security-events: write

concurrency:
  group: "docs-as-code-${{ github.event.repository.name }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  call-module:
    uses: sommerfeld-io/dev-environment-config/.github/workflows/module-docs-as-code.yml@v0.1.0-alpha.3

  on-failure:
    runs-on: ubuntu-latest
    needs: call-module
    if: failure()
    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
