---
# @file docs-as-code.yml
# @brief Github Actions workflow that generates Asciidoc documentation based on source code from this repo and updates the projects README file.
#
# @description This GitHub Actions workflow serves the purpose of generating Asciidoc documentation
# based on the source code from the repository and updating the project's ``README.adoc`` based on
# contents from the Antora docs. It is designed to automatically trigger whenever new code is pushed
# to the remote repository. Additionally, it is scheduled to run each night to ensure the
# documentation is up-to-date.
#
# The workflow acts as a self-contained automation for this repository, providing a seamless way to
# generate and update documentation whenever changes are made to the codebase. Moreover, its design
# allows it to be reused as a reusable workflow module for other repositories. This means that other
# projects can include this workflow, enabling them to have consistent and automated documentation
# generation.
#
# By utilizing this workflow, the project ensures that the Asciidoc documentation stays in sync with
# the latest code changes. This leads to improved documentation quality and better project
# understanding.
#
# == See also
#
# * Gthub docs on link:https://docs.github.com/en/actions/using-workflows/reusing-workflows[Reusable workflows]
name: Generate Docs (as Code)

on:
  push:
    # branches: [ "main", "feat/*", "release/*" ]
    branches-ignore:
      - dependabot/**
  workflow_call:

permissions:
  contents: write
  security-events: write

concurrency:
  group: "docs-as-code-${{ github.event.repository.name }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  info:
    name: info
    runs-on: ubuntu-latest
    steps:
      - name: Print repo name which runs the workflow
        run: echo "[INFO] repo = ${{ github.event.repository.name }}"
        shell: bash

  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print Branchname
        run: echo ${{github.ref}}
      - name: Adjust version in antora.yml
        uses: sebastian-sommerfeld-io/github-action-update-antora-yml@main
        with:
          git_ref: ${{github.ref}}
      - name: Run yamllint for docs/antora.yml
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: docs/antora.yml
      - name: README.adoc
        uses: sebastian-sommerfeld-io/github-action-generate-readme@main
        with:
          caption: ${{ github.event.repository.name }}
      - name: Generate docs from source code
        uses: sebastian-sommerfeld-io/github-action-generate-docs@main
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: sebastian
          author_email: sebastian@sommerfeld.io
          message: "[Actions Bot] docs: auto-generate docs"

  validate-links:
    runs-on: ubuntu-latest
    needs: generate-docs
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install asciidoc-link-check
        run: npm install --location=global asciidoc-link-check@1.0.15
      - name: Validate links in all adoc files
        run: find . -name '*.adoc' -exec asciidoc-link-check -c .adoc-links.json -p {} \;

  on-failure:
    runs-on: ubuntu-latest
    needs: ['info', 'generate-docs', 'validate-links']
    if: failure()
    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
