---
name: "Housekeeping: Repository"

on:
  schedule:
    - cron: '30 0 * * *' # https://crontab.guru
  push:
    branches:
      - main
    paths:
      - src/main/github-config/*
      - .github/workflows/housekeeping-repo.yml
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  info:
    name: info
    runs-on: ubuntu-latest
    steps:
      - name: Print repo name which runs the workflow
        run: echo "[INFO] repo = ${{ github.event.repository.name }}"
        shell: bash

  configure-repo:
    name: configure-repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure repository
        # run: |
        #   gh repo edit \sommerfeld-io/${{ github.event.repository.name }}
        #     --enable-discussions \
        #     --enable-issues \
        #     --enable-projects \
        #     --enable-wiki=false \
        #     --visibility=public
        run: |
          echo "[INFO] Get repo sommerfeld-io/${{ github.event.repository.name }}"
          gh api "repos/sommerfeld-io/${{ github.event.repository.name }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

  on-failure:
    runs-on: ubuntu-latest
    needs: ['info', 'configure-repo']
    if: failure()
    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
