---
# @file housekeeping-labels.yml
# @brief Github Actions workflow that ensures all mandatory labels are present for a repo and all obsolete labels are removed.
#
# @description The workflow, that is called this way, is responsible for deleting unnecessary
# labels and creating the required labels for issues and pull requests. By executing this workflow,
# it ensures a streamlined and organized labeling system, enabling effective categorization and
# tracking of tasks and contributions within your projects. Since the labels are managed through this
# workflow, the settings from link:https://github.com/organizations/sommerfeld-io/settings/repository-defaults[GitHub organizations label-config]
# don't take effect.


name: "Housekeeping: Labels"

on:
  schedule:
    - cron: '0 1 * * *' # https://crontab.guru
  push:
    branches:
      - main
    paths:
      - .github/workflows/housekeeping-labels.yml

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  call-workflow:
    uses: sommerfeld-io/dev-environment-config/.github/workflows/module-housekeeping-labels.yml@main

  on-failure:
    runs-on: ubuntu-latest
    needs: call-workflow
    if: failure()
    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
