---
# @file housekeeping-issues.yml
# @brief Github Actions workflow generates Asciidoc documentation based on source code from this repo and updates the projects README file.
#
# @description The workflow, that is called this way, handles the automatic assignment of newly
# created issues and pull requests to specific projects and users. By leveraging this workflow,
# tasks and contributions are efficiently tracked and assigned, ensuring clear ownership and
# streamlined collaboration within your development projects. It is designed to automatically
# trigger whenever new issues or Pull Requests are created.


name: "Housekeeping: Issues + PRs"

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
      - assigned

permissions:
  contents: read
  issues: write
  pull-requests: write
  repository-projects: write

jobs:
  call-workflow:
    uses: sommerfeld-io/dev-environment-config/.github/workflows/module-housekeeping-issues.yml@main
    secrets:
      GH_TOKEN_REPO_AND_PROJECT: ${{ secrets.GH_TOKEN_REPO_AND_PROJECT }}

  on-failure:
    runs-on: ubuntu-latest
    needs: call-workflow
    if: failure()
    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
