---
# @file module-release-validate-inputs.yml
# @brief Github Actions module to call from other workflows.
#
# @description This GitHub Actions workflow is designed to be a reusable workflow that functions
# as a component within other workflows. It cannot be triggered on its own but rather acts as
# part of larger workflows, specifically those related to "Deploy + Release" (``release.yml``).
#
# The main purpose of this workflow module is to validate the version that should be released,
# ensuring it adheres to the rules of semantic versioning. To accomplish this, the module utilizes
# the ``semver-action``, a tool that enforces semantic versioning rules and checks whether the
# proposed version follows the proper format.
#
# When integrated into a "Deploy + Release" workflow, this module serves as a gatekeeper for the
# release process. It prevents incorrect or invalid versions from being released and helps maintain
# versioning consistency across projects. By centralizing this validation logic into a reusable
# workflow, developers can ensure a consistent and reliable release process across different
# projects and workflows.
#
# == Example
#
# [source, yml]
#
# ....
# jobs:
#   call-workflow:
#     uses: sommerfeld-io/.github/.github/workflows/module-release-validate-inputs.yml@main
# ....
#
# == See also
#
# * Gthub docs on link:https://docs.github.com/en/actions/using-workflows/reusing-workflows[Reusable workflows]
# * link:https://github.com/sommerfeld-io/semver-action[Github repository] of the ``semver-action``
name: "Module: Release Validate Inputs"

on:
  workflow_call:

permissions:
  contents: read

jobs:
  info:
    name: info
    runs-on: ubuntu-latest
    steps:
      - name: Print repo name which runs the workflow
        run: echo "[INFO] repo = ${{ github.event.repository.name }}"
        shell: bash

  validate-inputs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Info
        run: |
          echo "Github Ref = ${{ github.ref }}"
          echo "Github Event = ${{ github.event_name }}"
          echo "Tag with version = ${{ github.event.inputs.version }}"
          echo "Publish Artifacts = ${{ github.event.inputs.publish }}"
        shell: bash
      - name: Validate version
        uses: sommerfeld-io/semver-action@main
        with:
          command: validate
          currentVersion: ${{ github.event.inputs.version }}
