---
# @file module-release-antora-version.yml
# @brief Github Actions module to call from other workflows.
#
# @description The purpose of this workflow module is to ensure that the documentation
# aligns accurately with the version of the repository's codebase as it is tagged. This
# synchronization is achieved by automatically updating the version information within
# the ``antora.yml`` configuration file. The version which is written to the ``antora.yml``
# is passed as an input parameter
#
# IMPORTANT: This workflow cannot be triggered on its own but rather acts as module for
# other, larger workflows.
#
# == How to use
#
# This module is intended to run as part of a "Deploy + Release" workflow (normally defined in a
# ``release.yml`` file)
#
# [source, yml]
#
# ....
# jobs:
#   update-version:
#     uses: sommerfeld-io/dev-environment-config/.github/workflows/module-release-antora-version.yml@main
#     permissions:
#       contents: write
#     with:
#       version: ${{ github.event.inputs.version }}
#
#   # ...
#
#   reset-version:
#     uses: sommerfeld-io/dev-environment-config/.github/workflows/module-release-antora-version.yml@main
#     permissions:
#       contents: write
#     with:
#       version: refs/heads/main
# ....
#
# == See also
#
# * Gthub docs on link:https://docs.github.com/en/actions/using-workflows/reusing-workflows[Reusable workflows]


name: "Module: Release (update version)"

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      file:
        required: false
        type: string
        default: docs/antora.yml

permissions:
  contents: write

jobs:
  write-to-antora-yml:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Print repo name which runs the workflow
        run: echo "[INFO] repo = ${{ github.event.repository.name }}"
        shell: bash
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Adjust version in ${{ inputs.file }}
        uses: sebastian-sommerfeld-io/github-action-update-antora-yml@main
        with:
          git_ref: ${{ inputs.version }}
          file: ${{ inputs.file }}
      - name: Run yamllint for ${{ inputs.file }}
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ${{ inputs.file }}
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: sebastian
          author_email: sebastian@sommerfeld.io
          message: "[Actions Bot] auto-generate version"
