---
# @file module-ci-lint.yml
# @brief Github Actions module to call from other workflows.
#
# @description This Reusable Workflow serves as a module that offers essential linter
# functionalities which are common to all repositories. This module is designed to be called from
# other workflows and never runs independently within the `.github` repository. By including this
# reusable workflow in other workflows, developers can easily incorporate common linting
# capabilities into their specific workflows, promoting code quality and adherence to predefined
# standards. It cannot be triggered on its own but rather acts as part of larger workflows,
# specifically those related to "CI" (``ci.yml``).
#
# There is no need to manage the linter rule sets on your own for each repository. The
# "Organization Housekeeping: Linter Rules" workflow guarantees that all required linter rule sets
# are present and up to date in every repository within the link:https://github.com/sommerfeld-io[sommerfeld.io organisation].
# This streamlined approach eliminates the burden of manually managing and updating rule sets in
# individual repositories, saving time and promoting code consistency.
#
# == Example
#
# [source, yml]
#
# ....
# jobs:
#   call-workflow:
#     uses: sommerfeld-io/.github/.github/workflows/module-ci-lint.yml@main
# ....
#
# == See also
#
# * Gthub docs on link:https://docs.github.com/en/actions/using-workflows/reusing-workflows[Reusable workflows]
name: "Module: CI Linter"

on:
  workflow_call:

permissions:
  contents: read

jobs:
  info:
    name: info
    runs-on: ubuntu-latest
    steps:
      - name: Print repo name which runs the workflow
        run: echo "[INFO] repo = ${{ github.event.repository.name }}"
        shell: bash

  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3

  lint-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run folderslint in container
        run: docker run -i --rm --volume "$(pwd):$(pwd)" --workdir "$(pwd)" sommerfeldio/folderslint:latest folderslint
        shell: bash

  lint-forbidden-folders:
    runs-on: ubuntu-latest
    if: github.event.repository.name != '.github'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Validate that no forbidden file / folder is present in repo
        run: |
          SUCCESS=true

          BLACKLIST=(
            # Folders
            '.github/ISSUE_TEMPLATE'
            # Files
            '.github/PULL_REQUEST_TEMPLATE.md'
          )
          for entry in "${BLACKLIST[@]}"
          do
            echo "[INFO] Check forbidden file / folder '$entry'"
            if [[ -e "$entry" ]]; then
              echo "[ERROR] File / folder '$entry' exists, but should be absent"
              SUCCESS=false
            fi
          done

          case $SUCCESS in
            (true)    echo "[INFO] SUCCESS" && exit 0;;
            (false)   echo "[ERROR] Detected forbidden files / folders" && exit 1;;
          esac
        shell: bash

  lint-filenames:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run ls-lint in container
        run: docker run -i --rm --volume "$(pwd):/data" --workdir "/data" lslintorg/ls-lint:1.11.0
        shell: bash

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          ignore_paths: node_modules target
